### PR TITLE
ace/validator: fix mountpoint checks

### LINKED ISSUE #464: ace: validator fails to detect mount points
Currently, the ACE validator checks if `/db` is a mount point since [it's defined as a mount point in the manifest](https://github.com/appc/spec/blob/0d1edc37553152577a56f256279992200f142b48/ace/image_manifest_main.json#L37).

It checks it's a mount point by calling `statfs()` on the directory and the parent and then comparing the f_fsid field. This check doesn't detect if a directory is a bind mount so it will error out mistakenly when the mount point is in the same filesystem as the parent:

```
# mkdir a b
# mount --bind a b
# stat --file-system b
File: "b"
    ID: df4743518d77c185 Namelen: 255     Type: ext2/ext3
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 116580597  Free: 32241161   Available: 32237065
Inodes: Total: 29622272   Free: 28560905
# stat --file-system b/..
File: "b/.."
    ID: df4743518d77c185 Namelen: 255     Type: ext2/ext3
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 116580597  Free: 32241161   Available: 32237065
Inodes: Total: 29622272   Free: 28560905
```

We could use [`name_to_handle_at()`](http://man7.org/linux/man-pages/man2/open_by_handle_at.2.html) or the [`mnt_id` flag in `/proc/[pid]/fdinfo/[fd]`](http://man7.org/linux/man-pages/man5/proc.5.html) but the former is not included in all kernels and the latter was added in Linux 3.15.

### PR DESCRIPTION
**Pull request by iaguis**
This includes:

- A proper check for Linux. The previous one was just checking if the
  devices were the same, this is not true for bind-mounts within the
  same device

- A check for FreeBSD courtesy of Maciej Pasternacki
  <maciej@3ofcoins.net>. Jails seem to have f_fsid set to zero so the
  original check didn't work. Now we check r_fstypename, f_mntfromname
  and f_mntonname too.

- As a fallback (for other systems) we do the same as the original code:
  just check the f_fsid.

Fixes #464 
cc @mpasternacki

### CODE REVIEW

**Comment by mpasternacki** [comment]
After adding the  missing `import "fmt"` in `os_shared.go`, works perfectly for me. :+1:

**Comment by iaguis** [comment]
Ooops, thanks for catching that!

File: ace/os_linux.go [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+	sc := bufio.NewScanner(mi)
+	for sc.Scan() {
+		var (
+			mountID        int
+			parentID       int
+			majorMinor     string
+			root           string
+			mountPoint     string
+			mountOptions   string
+			optionalFields string
```
Comment (alban) [inline ace/os_linux.go]: according to `proc(5)`:
> (7)  optional fields: zero or more fields of the form "tag[:value]".

Does the `Scanf` work if there are several fields? It would be good to add some unit tests about that.

**Comment by alban** [comment]
Except the issue with parsing `optionalFields`, it looks good.

File: ace/os_linux.go (hunk 1 above)
Comment (iaguis) [inline ace/os_linux.go]: It's probably fine because we only care about (5) but for that same reason we can only parse the first 5 fields (which are fixed) and avoid possible problems. I'll update the PR with that and some unit tests. Thanks!

**Comment by iaguis** [comment]
Updated with only parsing the first (6) fields and added a test

**Comment by jonboulle** [comment]
:+1: thanks
